using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

/// CONTRIBUTION:
/// Name:   Rishti Gupta
/// ASUID:  1217211814
/// Email:  rgupta75@asu.edu
/// Class:  CSE-445 (#96279)

///AND

/// Name:   Arun Deepak Chandrasekar
/// ASUID:  1217200647
/// Email:  achand66@asu.edu
/// Class:  CSE-445 (#96279)

namespace Project2_CSE445
{
    public static class Decoder
    {
        // Decodes the encoded order string using XmlSerializer.
        // Returns the same objects that were generated by the travel agency.
        public static OrderClass DecodeOrder(string encodedOrder)
        {
            XmlSerializer deserializer = new XmlSerializer(typeof(OrderClass));

            using (TextReader tr = new StringReader(encodedOrder))
            {
                return (OrderClass)deserializer.Deserialize(tr);
            }
        }
    }
}
